### ISSUE TITLE
I think I have a proof that for N >36 all sequences can be arranged as desired

### ISSUE THREAD

**Issue by schauder** [charlieturner/square-sum-sequences#1]
I'm wondering if this is something worthy of publication?
If so I'd love to do that, but since I'm a software developer I'd need help with that.

Would you be interested to cooperate on that?
If not I'd probably just publish it on my blog and be done with it. 

In any case, it would be great if you could take a look if I made a mistake in it.
The proof is really simple (otherwise I wouldn't be able to find it), so it probably doesn't take much of your time.

If interested drop me a line at jens at schauderhaft dot de

**Comment by Blauschirm** [comment]
oh man, please keep us updated on this ^^

**Comment by DelSquared** [comment]
In case you need any of it, I put together a repo [here](https://github.com/DelSquared/graph-misc-repo) with scripts to go through the graphs and calculate various properties such as the characteristic polynomials, number of edges, degree statistics, "entropy", etc.

**Comment by schauder** [comment]
I realized a fatal (and pretty stupid mistake) in my proof.

The idea was that once you have a graph with a Hamiltonian cycle, adding a number will create another Hamiltonian cycle. But it just creates a path and I mixed that up. => Sorry, no proof.
